/* Auto-generated by genmsg_cpp for file /home/gaurav/ros_tutorials/Inverse-Kinematics/PathPlanner/msg/configMessage.msg */
#ifndef PATHPLANNER_MESSAGE_CONFIGMESSAGE_H
#define PATHPLANNER_MESSAGE_CONFIGMESSAGE_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"


namespace PathPlanner
{
template <class ContainerAllocator>
struct configMessage_ : public ros::Message
{
  typedef configMessage_<ContainerAllocator> Type;

  configMessage_()
  : num(0)
  {
  }

  configMessage_(const ContainerAllocator& _alloc)
  : num(0)
  {
  }

  typedef int64_t _num_type;
  int64_t num;


private:
  static const char* __s_getDataType_() { return "PathPlanner/configMessage"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "57d3c40ec3ac3754af76a83e6e73127a"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int64 num\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, num);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, num);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(num);
    return size;
  }

  typedef boost::shared_ptr< ::PathPlanner::configMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::PathPlanner::configMessage_<ContainerAllocator>  const> ConstPtr;
}; // struct configMessage
typedef  ::PathPlanner::configMessage_<std::allocator<void> > configMessage;

typedef boost::shared_ptr< ::PathPlanner::configMessage> configMessagePtr;
typedef boost::shared_ptr< ::PathPlanner::configMessage const> configMessageConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::PathPlanner::configMessage_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::PathPlanner::configMessage_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace PathPlanner

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::PathPlanner::configMessage_<ContainerAllocator> > {
  static const char* value() 
  {
    return "57d3c40ec3ac3754af76a83e6e73127a";
  }

  static const char* value(const  ::PathPlanner::configMessage_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x57d3c40ec3ac3754ULL;
  static const uint64_t static_value2 = 0xaf76a83e6e73127aULL;
};

template<class ContainerAllocator>
struct DataType< ::PathPlanner::configMessage_<ContainerAllocator> > {
  static const char* value() 
  {
    return "PathPlanner/configMessage";
  }

  static const char* value(const  ::PathPlanner::configMessage_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::PathPlanner::configMessage_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int64 num\n\
";
  }

  static const char* value(const  ::PathPlanner::configMessage_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::PathPlanner::configMessage_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::PathPlanner::configMessage_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.num);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct configMessage_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::PathPlanner::configMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::PathPlanner::configMessage_<ContainerAllocator> & v) 
  {
    s << indent << "num: ";
    Printer<int64_t>::stream(s, indent + "  ", v.num);
  }
};


} // namespace message_operations
} // namespace ros

#endif // PATHPLANNER_MESSAGE_CONFIGMESSAGE_H

